source = ~/.config/hypr/mocha.conf
source = ~/.config/hypr/modules/keybindings.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/monitor.conf
source = ~/.config/hypr/modules/look.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/layout.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/mouse.conf
source = ~/.config/hypr/modules/windowrules.conf
