exec-once = /usr/libexec/polkit-gnome-authentication-agent-1

exec-once = hyprlock & hypridle

exec-once = hyprpaper & swaync & waybar

exec-once = elephant

exec-once = sh -c 'pgrep -x walker >/dev/null || exec walker --gapplication-service'
