# ----------------------------------------------------- 
# █▀█ █▀█ █▀█ █▀▀ █▀█ ▄▀█ █▀▄▀█ █▀
# █▀▀ █▀▄ █▄█ █▄█ █▀▄ █▀█ █░▀░█ ▄█
# -----------------------------------------------------
$terminal = kitty
$fileManager = kitty yazi
$menu = walker
